Redone Data Manager, fixed errors
StormlightTech/OpenCAD-php pull request #419
Opened 2022-06-12 23:05 UTC by kevingorman1000

Fixed lots of errors within several modules. 
Reworked Data Manager so now works from one dynamic PHP file. "*TypeManager.php" files within "oc-admin/dataManagement/" are no longer required.
Fixed install errors
Resolved SQL errors within dataActions.php
Resolved SQL file error

2022-06-13 16:04 UTC, kevingorman1000 commented
Database Entires: 

Duplicate entry within ncicweapons (nameId - UserId) Needed?
Duplicate Entry within ncicplate (nameId - UserId) Needed?
Typo column within ncicplate (vehSSecondaryolor - vehSecondaryColor)
Table doesn't follow naming convention (veh_model - vehModel)

2022-06-14 08:21 UTC, phillf commented
@kevingorman1000, are there any queries for `userid` in either ncic toolkit? I think there might be something. I would leave `userid` until it is proven it isn't required.

I am pretty sure that column is written to when ever a record is saved that way all weapons or vehicles can be pulled where a given `userid` is 1 for example.

2022-06-14 12:16 UTC, kevingorman1000 commented
From the looks of it, it links up to the users table. Which, as you stated, is correct. Go ahead and keep that table. No other NCIC table seems to have it apart from plates and weapons, should warnings, warrants etc not contain that column as well ?

2022-06-26 21:38 UTC, ItsAGeekThing commented on oc-admin/about.php
> +							<p>OpenCAD is an open source project licensed under GNU GPL v3. The original code and concept by <a rel="noopener" href="https://github.com/ossified" title="a link to the original developer's
We can probably drop the the reference to Overt Source. I'll get clarification on this with @phillf.

```suggestion
							<p>OpenCAD is an open source project licensed under GNU GPL v3. The original code and concept by <a rel="noopener" href="https://github.com/ossified" title="a link to the original developer's GitHub.">Shane Gill</a>.</p>
```

2022-06-26 21:38 UTC, ItsAGeekThing commented on oc-api/config/functions.inc.php
> +    http_response_code(201);
Set HTTP response status code to "401 Unauthorized".

```suggestion
    http_response_code(401);
```

2022-06-26 21:38 UTC, ItsAGeekThing commented on oc-config.sample.php
> +  define('OC_DEVELOP', true);
```suggestion
  define('OC_DEVELOP', false);
```

2022-06-26 21:38 UTC, ItsAGeekThing commented on oc-settings.php
> +define( 'APPLATESTVERSIONURL', "https://raw.githubusercontent.com/kevingorman1000/OpenCad-Versions-TEMP/main/version.json");
Perhaps this is something we could pull from the GitHub API or maybe even use a CloudFlare worker to create a API endpoint.

https://docs.github.com/en/rest/git/tags#get-a-tag

2022-06-26 21:40 UTC, kevingorman1000 commented on oc-settings.php
> +define( 'APPLATESTVERSIONURL', "https://raw.githubusercontent.com/kevingorman1000/OpenCad-Versions-TEMP/main/version.json");
This was intended to be a test feature for now as a "proof of concept". Obviously have to have discussions on the best way to implement it, if we implement it.

2022-06-26 21:52 UTC, ItsAGeekThing commented on oc-settings.php
> +define( 'APPLATESTVERSIONURL', "https://raw.githubusercontent.com/kevingorman1000/OpenCad-Versions-TEMP/main/version.json");
Absolutely.

We can open a separate issue for this to discuss it's (proposed) implementation later on. I'll go ahead and mark this resolved. 👍

2022-06-29 14:31 UTC, kevingorman1000 commented on oc-api/config/functions.inc.php
> +    http_response_code(201);
I forgot to reply to all of these comments. This has already been resolved, apparently I haven't pushed the updated version? Once I've worked on what I'm doing now, I'll push it with the resolved response code.

2022-07-04 14:25 UTC, phillf requested changes
Kevin, you need to pull changes from the upstream before this can be merged. Your README.md is out of date.

2022-07-04 15:33 UTC, kevingorman1000 commented
Readme has been updated, everything seems to be updated and correct. Let me know if any issues.

2022-07-04 15:36 UTC, phillf approved these changes

2022-07-04 15:40 UTC, phillf approved these changes

2022-07-04 15:41 UTC, merged